package Zaliczeniowe2.Utils;

import Zaliczeniowe2.domain.User;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class SimpleHyperSQL {
    private static Connection connect(){
        String url="jdbc:hsqldb:hsql://localhost/workdb";
        Connection connection = null;
        try {
            connection = DriverManager.getConnection(url);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return connection;
    }

    private static void initializeDatabase(){
        String createTableSql =
                "CREATE TABLE users("
                        + "id int GENERATED BY DEFAULT AS IDENTITY,"
                        + "login VARCHAR(200),"
                        + "password VARCHAR(200),"
                        + "email VARCHAR(200),"
                        + "permissionLevel INT"
                        + ")";
        Statement createTable = null;
        try {
            createTable = connect().createStatement();
            createTable.executeUpdate(createTableSql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static List<User> getUsers(){
        initializeDatabase();
        return new ArrayList<>();
    }
}
